# Site settings
title: Lnrlf
url: "http://Lnrlf.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: ljo030818@gmail.com
author: 탄율
avatar: "http://www.gameaz.co.kr/Files/Images/20180924/Screenshot20180924at16.45.192.jpg"
profile: hi~ 제5인격유저라구 ㅇㅅㅇ!
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  youtube: "https://www.youtube.com/results?search_query=%EC%A0%9C5%EC%9D%B8%EA%B2%A9"
  GitHub: "https://github.com/laobubu/jekyll-theme-EasyBook"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    game: /about/
    computer: /category/
    need a computer: http://jekyllthemes.org/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji   

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
